/*

SizedBox(height: 500),
_diagRow("AmuStabFront_AngleAdc", getCanValue('0x320', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuStabFront_AngleAct", getCanValue('0x320', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuUnderArmFront_AngleAdc", getCanValue('0x320', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuUnderArmFront_AngleAct", getCanValue('0x320', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),


_diagRow("AmuUpperArmFront_AngleAdc", getCanValue('0x321', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuUpperArmFront_AngleAct", getCanValue('0x321', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuCraneFrameFront_AngleAdc", getCanValue('0x321', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuCraneFrameFront_AngleAct", getCanValue('0x321', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),



 if (canIdExists('0x064')) ...[       
_diagRow("mRadioInp0", getCanBit('0x064', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioInp1", getCanBit('0x064', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioInp2", getCanBit('0x064', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioInp3", getCanBit('0x064', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioInp4", getCanBit('0x064', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioInp5", getCanBit('0x064', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadioInp6", getCanBit('0x064', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadioInp7", getCanBit('0x064', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadioInp8", getCanBit('0x064', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioInp9", getCanBit('0x064', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioInp10", getCanBit('0x064', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioInp11", getCanBit('0x064', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioInp12", getCanBit('0x064', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioInp13", getCanBit('0x064', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadioInp14", getCanBit('0x064', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadioInp15", getCanBit('0x064', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadioInp16", getCanBit('0x064', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioInp17", getCanBit('0x064', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioInp18", getCanBit('0x064', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioInp19", getCanBit('0x064', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioInp20", getCanBit('0x064', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioInp21", getCanBit('0x064', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadioInp22", getCanBit('0x064', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadioInp23", getCanBit('0x064', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadioInp24", getCanBit('0x064', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioInp25", getCanBit('0x064', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioInp26", getCanBit('0x064', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioInp27", getCanBit('0x064', byteIndex: 3, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioInp28", getCanBit('0x064', byteIndex: 3, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioInp29", getCanBit('0x064', byteIndex: 3, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadioInp30", getCanBit('0x064', byteIndex: 3, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadioInp31", getCanBit('0x064', byteIndex: 3, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadioInp32", getCanBit('0x064', byteIndex: 4, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioInp33", getCanBit('0x064', byteIndex: 4, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioInp34", getCanBit('0x064', byteIndex: 4, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioInp35", getCanBit('0x064', byteIndex: 4, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioInp36", getCanBit('0x064', byteIndex: 4, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioInpBattLow", getCanBit('0x064', byteIndex: 7, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioInpSE", getCanBit('0x064', byteIndex: 7, bitIndex: 4) ? "ON" : "OFF"),
 ],
  if (canIdExists('0x1E4')) ...[   
_diagRow("RadioCH8", getCanValue('0x1E4', byteIndex: 0, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("RadioCH7", getCanValue('0x1E4', byteIndex: 1, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("RadioCH6", getCanValue('0x1E4', byteIndex: 2, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("RadioCH5", getCanValue('0x1E4', byteIndex: 3, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("RadioCH4", getCanValue('0x1E4', byteIndex: 4, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("RadioCH3", getCanValue('0x1E4', byteIndex: 5, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("RadioCH2", getCanValue('0x1E4', byteIndex: 6, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("RadioCH1", getCanValue('0x1E4', byteIndex: 7, length: 1, scale: 1).toStringAsFixed(0)),
],

if (canIdExists('0x2E4')) ...[  
_diagRow("Radio1Stop", getCanValue('0x2E4', byteIndex: 0, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("mRadio1inpA1", getCanBit('0x2E4', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio1inpA2", getCanBit('0x2E4', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadio1inpA3", getCanBit('0x2E4', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadio1inpA4", getCanBit('0x2E4', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadio1inpA5", getCanBit('0x2E4', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadio1inpA6", getCanBit('0x2E4', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadio1inpA7", getCanBit('0x2E4', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadio1inpA8", getCanBit('0x2E4', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("mRadio1inpB1", getCanBit('0x2E4', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio1inpB2", getCanBit('0x2E4', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadio1inpB3", getCanBit('0x2E4', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadio1inpB4", getCanBit('0x2E4', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadio1inpB5", getCanBit('0x2E4', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadio1inpB6", getCanBit('0x2E4', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadio1inpB7", getCanBit('0x2E4', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadio1inpB8", getCanBit('0x2E4', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("mRadio1inpC1", getCanBit('0x2E4', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio1inpC2", getCanBit('0x2E4', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadio1inpC3", getCanBit('0x2E4', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadio1inpC4", getCanBit('0x2E4', byteIndex: 3, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadio1inpC5", getCanBit('0x2E4', byteIndex: 3, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadio1inpC6", getCanBit('0x2E4', byteIndex: 3, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadio1inpC7", getCanBit('0x2E4', byteIndex: 3, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadio1inpC8", getCanBit('0x2E4', byteIndex: 3, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("mRadio1inpCTRL1", getCanBit('0x2E4', byteIndex: 7, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio1inpCTRL2", getCanBit('0x2E4', byteIndex: 7, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadio1inpCTRL3", getCanBit('0x2E4', byteIndex: 7, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadio1inpTimeStop", getCanBit('0x2E4', byteIndex: 7, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadio1inpSafetyStop", getCanBit('0x2E4', byteIndex: 7, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadio1inpStop", getCanBit('0x2E4', byteIndex: 7, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadio1inpStart", getCanBit('0x2E4', byteIndex: 7, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadio1inpHorn", getCanBit('0x2E4', byteIndex: 7, bitIndex: 7) ? "ON" : "OFF"),
],
if (canIdExists('0x18A')) ...[ 
_diagRow("mRadioS1", getCanBit('0x18A', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioS2", getCanBit('0x18A', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioS3", getCanBit('0x18A', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioS4", getCanBit('0x18A', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioS5", getCanBit('0x18A', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioS6", getCanBit('0x18A', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioS7", getCanBit('0x18A', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioS8", getCanBit('0x18A', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioS27", getCanBit('0x18A', byteIndex: 3, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioS28", getCanBit('0x18A', byteIndex: 3, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioStart", getCanBit('0x18A', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
],

if (canIdExists('0x38A')) ...[ 
_diagRow("mRadioY10", getCanBit('0x38A', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioY11", getCanBit('0x38A', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioY12", getCanBit('0x38A', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioY13", getCanBit('0x38A', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadioY14", getCanBit('0x38A', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadioY15", getCanBit('0x38A', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadioY16", getCanBit('0x38A', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadioY17", getCanBit('0x38A', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioY18", getCanBit('0x38A', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioY19", getCanBit('0x38A', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioY20", getCanBit('0x38A', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioY21", getCanBit('0x38A', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadioY22", getCanBit('0x38A', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadioY23", getCanBit('0x38A', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadioY25", getCanBit('0x38A', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadioY26", getCanBit('0x38A', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadioY27", getCanBit('0x38A', byteIndex: 3, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadioY28", getCanBit('0x38A', byteIndex: 3, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadioY29", getCanBit('0x38A', byteIndex: 3, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadioY30", getCanBit('0x38A', byteIndex: 3, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mRadioY31", getCanBit('0x38A', byteIndex: 3, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadioBattLow", getCanBit('0x38A', byteIndex: 7, bitIndex: 1) ? "ON" : "OFF"),
],

if (canIdExists('0x18A')) ...[
_diagRow("mRadio4_S0", getCanBit('0x18B', byteIndex: 5, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRadio4_S1", getCanBit('0x18B', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio4_S2", getCanBit('0x18B', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio4_S3", getCanBit('0x18B', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadio4_S4", getCanBit('0x18B', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadio4_S5", getCanBit('0x18B', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadio4_S6", getCanBit('0x18B', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadio4_S7", getCanBit('0x18B', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadio4_S8", getCanBit('0x18B', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mRadio4_S16", getCanBit('0x18B', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("mRadio4_S17", getCanBit('0x18B', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRadio4_S18", getCanBit('0x18B', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRadio4_S32", getCanBit('0x18B', byteIndex: 4, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio4_S36", getCanBit('0x18B', byteIndex: 4, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadio4_S40", getCanBit('0x18B', byteIndex: 5, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio4_S44", getCanBit('0x18B', byteIndex: 5, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mRadio4_CAN_ENABLE", getCanBit('0x18B', byteIndex: 7, bitIndex: 3) ? "ON" : "OFF"),
],
if (canIdExists('0x38A')) ...[
_diagRow("mRadio4_START", getCanBit('0x38B', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mRadio4_Acc",   getCanBit('0x38B', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
],

_diagRow("AppFront_VersionA", getCanValue('0x310', byteIndex: 0, length: 1, scale: 1).toString()),
_diagRow("AppFront_VersionB", getCanValue('0x310', byteIndex: 1, length: 1, scale: 1).toString()),
_diagRow("AppFront_VersionC", getCanValue('0x310', byteIndex: 2, length: 1, scale: 1).toString()),
_diagRow("AppFront_VersionDay", getCanValue('0x310', byteIndex: 3, length: 1, scale: 1).toString()),
_diagRow("AppFront_VersionMonth", getCanValue('0x310', byteIndex: 4, length: 1, scale: 1).toString()),
_diagRow("AppFront_VersionYear", getCanValue('0x310', byteIndex: 5, length: 2, scale: 1).toString()),
_diagRow("Front_PrjVersion", getCanValue('0x310', byteIndex: 7, length: 1, scale: 1).toString()),


_diagRow("pressFront_PistonSide_Adc", getCanValue('0x311', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("pressFront_PistonSide_Act", getCanValue('0x311', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("pressFront_RodSide_Adc", getCanValue('0x311', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("pressFront_RodSide_Act", getCanValue('0x311', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),


_diagRow("sqFront_Twistlock1", getCanBit('0x312', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("sqFront_Twistlock2", getCanBit('0x312', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("sqFront_ArmTelesIn", getCanBit('0x312', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("sqFront_ExtraLegC2", getCanBit('0x312', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("sqFront_ExtraLegC1", getCanBit('0x312', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("sqFront_StabGround", getCanBit('0x312', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("sqFront_CloggedFilter", getCanBit('0x312', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("sqFront_TwistlockSpreader1", getCanBit('0x312', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("sqFront_TwistlockSpreader2", getCanBit('0x312', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("sqFront_2040_1", getCanBit('0x312', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("sqFront_2040_2", getCanBit('0x312', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("sqFront_Swing", getCanBit('0x312', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("sqFront_BinStabStowed", getCanBit('0x312', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),


_diagRow("Display_Reply", getCanValue('0x162', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_ReplyCnt", getCanValue('0x162', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_ReplyA", getCanValue('0x162', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_ReplyB", getCanValue('0x162', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),


_diagRow("FrontPwrSupply", getCanValue('0x313', byteIndex: 0, length: 2, scale: 1).toString()),
_diagRow("FrontVPwrA", getCanValue('0x313', byteIndex: 2, length: 2, scale: 1).toString()),
_diagRow("FrontVPwrB", getCanValue('0x313', byteIndex: 4, length: 2, scale: 1).toString()),
_diagRow("FrontVPwrCD", getCanValue('0x313', byteIndex: 6, length: 2, scale: 1).toString()),

_diagRow("yvpFront_OutUnderArm_V", getCanValue('0x315', byteIndex: 0, length: 2, scale: 1).toString()),
_diagRow("yvpFront_InUnderArm_V", getCanValue('0x315', byteIndex: 2, length: 2, scale: 1).toString()),
_diagRow("yvpFront_OutOverArm_V", getCanValue('0x315', byteIndex: 4, length: 2, scale: 1).toString()),
_diagRow("yvpFront_InOverArm_V", getCanValue('0x315', byteIndex: 6, length: 2, scale: 1).toString()),

_diagRow("yvpFront_ExtensionArmOut_V", getCanValue('0x316', byteIndex: 0, length: 2, scale: 1).toString()),
_diagRow("yvpFront_ExtensionArmIn_V", getCanValue('0x316', byteIndex: 2, length: 2, scale: 1).toString()),
_diagRow("yvpFront_Cont20_V", getCanValue('0x316', byteIndex: 4, length: 2, scale: 1).toString()),
_diagRow("yvpFront_Cont40_V", getCanValue('0x316', byteIndex: 6, length: 2, scale: 1).toString()),

_diagRow("yvFront_ExtraLegOut_V", getCanBit('0x317', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvFront_ExtraLegIn_V", getCanBit('0x317', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("kStopEngineCommand_V", getCanBit('0x317', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("kBeaconLamp_V", getCanBit('0x317', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("kPTO_V", getCanBit('0x317', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("kWorkLamp_V", getCanBit('0x317', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("yvFront_Twistlock1_V", getCanBit('0x317', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("yvFront_Twistlock2_V", getCanBit('0x317', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("yvFront_Regen_V", getCanBit('0x317', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvFront_ExtensionStabOut_V", getCanBit('0x317', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("yvFront_ExtensionStabIn_V", getCanBit('0x317', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("yvFront_ExtraLegDown_V", getCanBit('0x317', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("yvFront_ExtraLegUp_V", getCanBit('0x317', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("yvFront_PivotStabOut_V", getCanBit('0x317', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("yvFront_PivotStabIn_V", getCanBit('0x317', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("yvFront_AUX3_V", getCanBit('0x317', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("yvFront_AUX4_V", getCanBit('0x317', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("kFlashExtraLeg_V", getCanBit('0x317', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("yvFront_20CH_V", getCanBit('0x317', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("yvFront_40CH_V", getCanBit('0x317', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("yvFront_Translation_V", getCanBit('0x317', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("yvFront_AUX8_V", getCanBit('0x317', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),



_diagRow("AmuStabFront_AngleAdc", getCanValue('0x320', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuStabFront_AngleAct", getCanValue('0x320', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuUnderArmFront_AngleAdc", getCanValue('0x320', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuUnderArmFront_AngleAct", getCanValue('0x320', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),


_diagRow("AmuUpperArmFront_AngleAdc", getCanValue('0x321', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuUpperArmFront_AngleAct", getCanValue('0x321', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuCraneFrameFront_AngleAdc", getCanValue('0x321', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("AmuCraneFrameFront_AngleAct", getCanValue('0x321', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),


_diagRow("AL_Front_CrcPar", getCanBit('0x325', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("AL_Front_CrcPrg", getCanBit('0x325', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("AL_Front_CrcTab", getCanBit('0x325', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("AL_Front_CrcRun", getCanBit('0x325', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("AL_Front_CrcRam", getCanBit('0x325', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("AL_Front_DataCPU0CPU1", getCanBit('0x325', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("AL_Front_TOut_AmuStabFront", getCanBit('0x325', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("AL_Front_TOut_AmuUnderArmFront", getCanBit('0x325', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("AL_Front_TOut_AmuUpperArmFront", getCanBit('0x325', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("AL_Front_FaultAmuStabFront", getCanBit('0x325', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("AL_Front_FaultAmuUnderArmFront", getCanBit('0x325', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("AL_Front_FaultAmuUpperArmFront", getCanBit('0x325', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("AL_Front_pressFront_RodSide_TMin", getCanBit('0x325', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("AL_Front_pressFront_RodSide_TMax", getCanBit('0x325', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("AL_Front_pressFront_PistonSide_TMin", getCanBit('0x325', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("AL_Front_pressFront_PistonSide_TMax", getCanBit('0x325', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("AL_Front_RELAY_WDO_OFF", getCanBit('0x325', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("AL_Front_MinOutputsPower", getCanBit('0x325', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("AL_Front_TOut_AmuCraneFrameFront", getCanBit('0x325', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("AL_Front_FaultAmuCraneFrameFront", getCanBit('0x325', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("AL_FRONT_MAIN_FAULT", getCanBit('0x325', byteIndex: 7, bitIndex: 0) ? "ON" : "OFF"),


_diagRow("msgFrontNewAMU", getCanBit('0x330', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),

_diagRow("JoyFront_Lb_Adc", getCanValue('0x360', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("JoyFront_Ub_Adc", getCanValue('0x360', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("JoyFront_2040_Adc", getCanValue('0x360', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("mEnable_UnderArmFront", getCanBit('0x360', byteIndex: 6, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mEnable_UpperArmFront", getCanBit('0x360', byteIndex: 6, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mEnable_2040_TeleFront", getCanBit('0x360', byteIndex: 6, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mEnable_Ub_ExtFront", getCanBit('0x360', byteIndex: 6, bitIndex: 8) ? "ON" : "OFF"),
_diagRow("mEnable_ChassisFront", getCanBit('0x360', byteIndex: 6, bitIndex: 16) ? "ON" : "OFF"),

_diagRow("mPivotStabOut_F", getCanBit('0x361', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mPivotStabIn_F", getCanBit('0x361', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mExtensionStabOut_F", getCanBit('0x361', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mExtensionStabIn_F", getCanBit('0x361', byteIndex: 0, bitIndex: 8) ? "ON" : "OFF"),
_diagRow("mExtraLegDown_F", getCanBit('0x361', byteIndex: 0, bitIndex: 16) ? "ON" : "OFF"),
_diagRow("mExtraLegUp_F", getCanBit('0x361', byteIndex: 0, bitIndex: 32) ? "ON" : "OFF"),
_diagRow("mExtraLegOut_F", getCanBit('0x361', byteIndex: 0, bitIndex: 64) ? "ON" : "OFF"),
_diagRow("mExtraLegIn_F", getCanBit('0x361', byteIndex: 0, bitIndex: 128) ? "ON" : "OFF"),

_diagRow("mEmergency1_F", getCanBit('0x361', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mEmergency2_F", getCanBit('0x361', byteIndex: 1, bitIndex: 8) ? "ON" : "OFF"),
_diagRow("mWorkLamp_F", getCanBit('0x361', byteIndex: 1, bitIndex: 16) ? "ON" : "OFF"),
_diagRow("mBeaconLamp_F", getCanBit('0x361', byteIndex: 1, bitIndex: 32) ? "ON" : "OFF"),
_diagRow("mPTO_F", getCanBit('0x361', byteIndex: 1, bitIndex: 64) ? "ON" : "OFF"),
_diagRow("mStopEngineCommand_F", getCanBit('0x361', byteIndex: 1, bitIndex: 128) ? "ON" : "OFF"),

_diagRow("mTwistlock1_F", getCanBit('0x361', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mTwistlock2_F", getCanBit('0x361', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mRegen_F", getCanBit('0x361', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mAUX3_F", getCanBit('0x361', byteIndex: 2, bitIndex: 8) ? "ON" : "OFF"),
_diagRow("mAUX4_F", getCanBit('0x361', byteIndex: 2, bitIndex: 16) ? "ON" : "OFF"),
_diagRow("mFlashExtraLeg_F", getCanBit('0x361', byteIndex: 2, bitIndex: 32) ? "ON" : "OFF"),
_diagRow("mFront_20CH", getCanBit('0x361', byteIndex: 2, bitIndex: 64) ? "ON" : "OFF"),
_diagRow("mFront_40CH", getCanBit('0x361', byteIndex: 2, bitIndex: 128) ? "ON" : "OFF"),

_diagRow("mFront_Translation", getCanBit('0x361', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mAUX8_F", getCanBit('0x361', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),

_diagRow("JoyFront_UbExt_Adc", getCanValue('0x361', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Joy_Chassis_Adc", getCanValue('0x361', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),


_diagRow("mRearSecurityDisable", getCanBit('0x362', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mRearEmergency", getCanBit('0x362', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mStopUnderOverArmMove", getCanBit('0x362', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mStopStabiMove", getCanBit('0x362', byteIndex: 0, bitIndex: 8) ? "ON" : "OFF"),
_diagRow("mAutoFrontOverArmUp", getCanBit('0x362', byteIndex: 0, bitIndex: 16) ? "ON" : "OFF"),
_diagRow("mStopFrontAnticollision", getCanBit('0x362', byteIndex: 0, bitIndex: 32) ? "ON" : "OFF"),

_diagRow("timerF_Gas_20", getCanValue('0x362', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("timerF_Gas_40", getCanValue('0x362', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),




_diagRow("Display_Key_F1", getCanBit('0x490', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_Key_F2", getCanBit('0x490', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_Key_F3", getCanBit('0x490', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_Key_F4", getCanBit('0x490', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("Display_Key_F5", getCanBit('0x490', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_Key_F6", getCanBit('0x490', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("Display_Key_F7", getCanBit('0x490', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("Display_Key_F8", getCanBit('0x490', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("Display_Key_F9", getCanBit('0x490', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_Key_F10", getCanBit('0x490', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),

_diagRow("Display_Key_OverArmUp", getCanBit('0x490', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_Key_OverArmDown", getCanBit('0x490', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_Key_UnderArmUp", getCanBit('0x490', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_Key_UnderArmDown", getCanBit('0x490', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("Display_Key_StabUp", getCanBit('0x490', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_Key_StabDown", getCanBit('0x490', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("Display_Key_StabOut", getCanBit('0x490', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("Display_Key_StabIn", getCanBit('0x490', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("Display_Key_ExtraLegOut", getCanBit('0x490', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_Key_ExtraLegIn", getCanBit('0x490', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_Key_Start", getCanBit('0x490', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_Key_RPM", getCanBit('0x490', byteIndex: 3, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("Display_Key_C20", getCanBit('0x490', byteIndex: 3, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_Key_C40", getCanBit('0x490', byteIndex: 3, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("Display_Key_Front", getCanBit('0x490', byteIndex: 3, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("Display_Key_Rear", getCanBit('0x490', byteIndex: 3, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("Display_mKeyOn", getCanBit('0x490', byteIndex: 4, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_Key_Both", getCanBit('0x490', byteIndex: 5, bitIndex: 16) ? "ON" : "OFF"),


_diagRow("Display_mEnableEquipFrontTareWeight", getCanBit('0x491', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_mEnableEquipRearTareWeight", getCanBit('0x491', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_mEnablePageWeightSettings", getCanBit('0x491', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),


_diagRow("Display_Order", getCanValue('0x155', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_OrderCnt", getCanValue('0x155', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_OrderA", getCanValue('0x155', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_OrderB", getCanValue('0x155', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("CmdP1", getCanBit('0x30A', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("CmdP2", getCanBit('0x30A', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("CmdP3", getCanBit('0x30A', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("CmdP4", getCanBit('0x30A', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),


_diagRow("CmdRearGreenLed", getCanBit('0x364', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("CmdFrontGreenLed", getCanBit('0x364', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("CmdRearRedLed", getCanBit('0x364', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("CmdFrontRedLed", getCanBit('0x364', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),


_diagRow("AppRear_VersionA",  getCanValue('0x340', byteIndex: 0, length: 1, scale: 1).toStringAsFixed(0),),
_diagRow( "AppRear_VersionB",  getCanValue('0x340', byteIndex: 1, length: 1, scale: 1).toStringAsFixed(0),),
_diagRow( "AppRear_VersionC",  getCanValue('0x340', byteIndex: 2, length: 1, scale: 1).toStringAsFixed(0),),
_diagRow( "AppRear_VersionDay",  getCanValue('0x340', byteIndex: 3, length: 1, scale: 1).toStringAsFixed(0),),
_diagRow( "AppRear_VersionMonth",  getCanValue('0x340', byteIndex: 4, length: 1, scale: 1).toStringAsFixed(0),),
_diagRow( "AppRear_VersionYear",  getCanValue('0x340', byteIndex: 5, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "Rear_PrjVersion",  getCanValue('0x340', byteIndex: 7, length: 1, scale: 1).toStringAsFixed(0),),

_diagRow("pressRear_PistonSide_Adc",  getCanValue('0x341', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "pressRear_PistonSide_Act",  getCanValue('0x341', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "pressRear_RodSide_Adc",  getCanValue('0x341', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "pressRear_RodSide_Act",  getCanValue('0x341', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0),),

_diagRow("sqRear_Twistlock1", getCanBit('0x342', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("sqRear_Twistlock2", getCanBit('0x342', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("sqRear_ArmTelesIn", getCanBit('0x342', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("sqRear_ExtraLegC2", getCanBit('0x342', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("sqRear_StabGround", getCanBit('0x342', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("sqRear_ExtraLegC1", getCanBit('0x342', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("sqRear_CloggedFilter", getCanBit('0x342', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("sqRear_TwistlockSpreader1", getCanBit('0x342', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("sqRear_TwistlockSpreader2", getCanBit('0x342', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("sqRear_2040_1", getCanBit('0x342', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("sqRear_2040_2", getCanBit('0x342', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("sqRear_AutoLubrification", getCanBit('0x342', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("sqRear_Swing", getCanBit('0x342', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("saEmergency_NC", getCanBit('0x341', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("saEmergency_NO", getCanBit('0x342', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("sqContainerDetect", getCanBit('0x342', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("sqRear_BinStabStowed", getCanBit('0x342', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mContainerOn", getCanBit('0x342', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),

_diagRow("RearPwrSupply",  getCanValue('0x343', byteIndex: 0, length: 2, scale: 0.1).toStringAsFixed(1),),
_diagRow( "RearVPwrA",  getCanValue('0x343', byteIndex: 2, length: 2, scale: 0.1).toStringAsFixed(1),),
_diagRow( "RearVPwrB",  getCanValue('0x343', byteIndex: 4, length: 2, scale: 0.1).toStringAsFixed(1),),
_diagRow( "RearVPwrCD",  getCanValue('0x343', byteIndex: 6, length: 2, scale: 0.1).toStringAsFixed(1),),

_diagRow("yvpRear_OutUnderArm_V",  getCanValue('0x345', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "yvpRear_InUnderArm_V",  getCanValue('0x345', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "yvpRear_OutOverArm_V",  getCanValue('0x345', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "yvpRear_InOverArm_V",  getCanValue('0x345', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0),),

_diagRow("yvpRear_ExtensionArmOut_V",  getCanValue('0x346', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "yvpRear_ExtensionArmIn_V",  getCanValue('0x346', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "yvpRear_Cont20_V",  getCanValue('0x346', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "yvpRear_Cont40_V",  getCanValue('0x346', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0),),

_diagRow("yvRear_ExtraLegOut_V",        getCanBit('0x347', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvRear_ExtraLegIn_V",         getCanBit('0x347', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("kStartEngine_V",              getCanBit('0x347', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("kBeaconLamp_V",               getCanBit('0x347', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("kPTO_V",                       getCanBit('0x347', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("kWorkLamp_V",                  getCanBit('0x347', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("yvRear_Twistlock1_V",         getCanBit('0x347', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("yvRear_Twistlock2_V",         getCanBit('0x347', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("yvRear_Regen_V",              getCanBit('0x347', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvRear_ExtensionStabOut_V",   getCanBit('0x347', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("yvRear_ExtensionStabIn_V",    getCanBit('0x347', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("yvRear_ExtraLegDown_V",       getCanBit('0x347', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("yvRear_ExtraLegUp_V",         getCanBit('0x347', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("yvRear_PivotStabOut_V",       getCanBit('0x347', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("yvRear_PivotStabIn_V",        getCanBit('0x347', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("yvRear_AUX3_V",               getCanBit('0x347', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("yvRear_AUX4_V",               getCanBit('0x347', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvRear_AUX8_V",               getCanBit('0x347', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("yvRear_NoTransportPosition_V",getCanBit('0x347', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("yvRear_TransportPosition_V",  getCanBit('0x347', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("kFlashExtraLeg_V",             getCanBit('0x347', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("yvRear_Translation_V",         getCanBit('0x347', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),

_diagRow("AmuStabRear_AngleAdc",  getCanValue('0x350', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "AmuStabRear_AngleAc",  getCanValue('0x350', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "AmuUnderArmRear_AngleAdc",  getCanValue('0x350', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "AmuUnderArmRear_AngleAct",  getCanValue('0x350', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0),),

_diagRow("AmuUpperArmRear_AngleAdc",  getCanValue('0x351', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "AmuUpperArmRear_AngleAct",  getCanValue('0x351', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "AmuCraneFrameRear_AngleAdc",  getCanValue('0x351', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "AmuCraneFrameRear_AngleAct",  getCanValue('0x351', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0),),

_diagRow("AL_Rear_CrcPar", getCanBit('0x355', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("AL_Rear_CrcPrg", getCanBit('0x355', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("AL_Rear_CrcTab", getCanBit('0x355', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("AL_Rear_CrcRun", getCanBit('0x355', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("AL_Rear_CrcRam", getCanBit('0x355', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("AL_Rear_DataCPU0CPU1", getCanBit('0x355', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("AL_Rear_Rdn_Emergency", getCanBit('0x355', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),

_diagRow("AL_Rear_TOut_AmuStabRear", getCanBit('0x355', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_AmuUnderArmRear", getCanBit('0x355', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_AmuUpperArmRear", getCanBit('0x355', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("AL_Rear_FaultAmuStabRear", getCanBit('0x355', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("AL_Rear_FaultAmuUnderArmRear", getCanBit('0x355', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("AL_Rear_FaultAmuUpperArmRear", getCanBit('0x355', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("AL_Rear_pressRear_RodSide_TMin", getCanBit('0x355', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("AL_Rear_pressRear_RodSide_TMax", getCanBit('0x355', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("AL_Rear_pressRear_PistonSide_TMin", getCanBit('0x355', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("AL_Rear_pressRear_PistonSide_TMax", getCanBit('0x355', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_Radio0_tx_0", getCanBit('0x355', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_Radio1_tx_0", getCanBit('0x355', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_Radio1_tx_1", getCanBit('0x355', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_MC2M_FRONT_IN1", getCanBit('0x355', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_MC2M_FRONT_IN2", getCanBit('0x355', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_MC2M_FRONT_AMU1", getCanBit('0x355', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("AL_Rear_TOut_MC2M_FRONT_AMU2", getCanBit('0x355', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_MC2M_FRONT_AL1", getCanBit('0x355', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("AL_Rear_RELAY_WDO_OFF", getCanBit('0x355', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("AL_Rear_MinOutputsPower", getCanBit('0x355', byteIndex: 3, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("AL_Rear_NoParametersValue", getCanBit('0x355', byteIndex: 3, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_RADIO3_TPDO3", getCanBit('0x355', byteIndex: 3, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("AL_Rear_TOut_AmuCraneFrameRear", getCanBit('0x355', byteIndex: 3, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("AL_Rear_FaultAmuCraneFrameRear", getCanBit('0x355', byteIndex: 3, bitIndex: 7) ? "ON" : "OFF"),

_diagRow("JoyFront_Lb_Adc",  getCanValue('0x360', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "JoyFront_Ub_Adc",  getCanValue('0x360', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "JoyFront_2040_Adc",  getCanValue('0x360', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow("mEnable_Lb_AmpFront", getCanBit('0x360', byteIndex: 6, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("mEnable_Ub_AmpFront", getCanBit('0x360', byteIndex: 6, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mEnable_2040_TeleFront", getCanBit('0x360', byteIndex: 6, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mEnable_Ub_ExtFront", getCanBit('0x360', byteIndex: 6, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mEnable_ChassisFront", getCanBit('0x360', byteIndex: 6, bitIndex: 4) ? "ON" : "OFF"),

_diagRow("yvFront_PivotStabOut", getCanBit('0x361', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("yvFront_PivotStabIn", getCanBit('0x361', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("yvFront_ExtensionStabOut", getCanBit('0x361', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvFront_ExtensionStabIn", getCanBit('0x361', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("yvFront_ExtraLegDown", getCanBit('0x361', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("yvFront_ExtraLegUp", getCanBit('0x361', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("yvFront_ExtraLegOut", getCanBit('0x361', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("yvFront_ExtraLegIn", getCanBit('0x361', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("yvFront_Emergency1", getCanBit('0x361', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvFront_Emergency2", getCanBit('0x361', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("kFrontWorkLamp", getCanBit('0x361', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("kFrontBeaconLamp", getCanBit('0x361', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("kFrontPTO", getCanBit('0x361', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("kFrontStopEngineCommand", getCanBit('0x361', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),
_diagRow("yvFront_Twistlock1", getCanBit('0x361', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("yvFront_Twistlock2", getCanBit('0x361', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("yvFront_Regen", getCanBit('0x361', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("yvFront_AUX3", getCanBit('0x361', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("yvFront_AUX4", getCanBit('0x361', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("kFrontFlashExtraLeg", getCanBit('0x361', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("yvFront_Translation", getCanBit('0x361', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("yvFront_AUX8", getCanBit('0x361', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),

_diagRow( "JoyFront_UbExt_Adc",  getCanValue('0x361', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "JoyFront_Chassis_Adc",  getCanValue('0x361', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0),),

_diagRow("mSecurityDisable", getCanBit('0x362', byteIndex: 0, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("saEmergency_NC", getCanBit('0x362', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("mStopUnderOverArmMove", getCanBit('0x362', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("mStopStabiMove", getCanBit('0x362', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mAutoFrontOverArmUp", getCanBit('0x362', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("mStopFrontAnticollision", getCanBit('0x362', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow( "timerF_Gas_20",  getCanValue('0x362', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0),),
_diagRow( "timerF_Gas_40",  getCanValue('0x362', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0),),


_diagRow("Display_ActualLoad", getCanValue('0x401', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_MaxLoad", getCanValue('0x401', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_curSwlFront", getCanValue('0x401', byteIndex: 4, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_curSwlRear", getCanValue('0x401', byteIndex: 5, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_Msg", getCanValue('0x401', byteIndex: 6, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_IconStop", getCanValue('0x401', byteIndex: 7, length: 1, scale: 1).toStringAsFixed(0)),

// Byte 0 – Flags
_diagRow("Display_IconStabFront", getCanBit('0x402', byteIndex: 0, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_IconStabRear", getCanBit('0x402', byteIndex: 0, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_IconFrontCrane", getCanBit('0x402', byteIndex: 0, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("Display_IconRearCrane", getCanBit('0x402', byteIndex: 0, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_IconWorkLight", getCanBit('0x402', byteIndex: 0, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("Display_IconDisableWeight", getCanBit('0x402', byteIndex: 0, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("Display_SecurityDisable", getCanBit('0x402', byteIndex: 0, bitIndex: 7) ? "ON" : "OFF"),

// Byte 1 – Flags
_diagRow("Display_Buzzer", getCanBit('0x402', byteIndex: 1, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_mEmerg", getCanBit('0x402', byteIndex: 1, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_StandByMode", getCanBit('0x402', byteIndex: 1, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_mLowBatteryRemote", getCanBit('0x402', byteIndex: 1, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("Display_mCycle", getCanBit('0x402', byteIndex: 1, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_mDT_Update", getCanBit('0x402', byteIndex: 1, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("Display_IconTransportFront", getCanBit('0x402', byteIndex: 1, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("Display_IconTransportRear", getCanBit('0x402', byteIndex: 1, bitIndex: 7) ? "ON" : "OFF"),

// Byte 2 – Flags
_diagRow("Display_mFOverArmTransport", getCanBit('0x402', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_mFUnderArmTransport", getCanBit('0x402', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_mFStabGround", getCanBit('0x402', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_mFStabiTransport", getCanBit('0x402', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("Display_mROverArmTransport", getCanBit('0x402', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_mRUnderArmTransport", getCanBit('0x402', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("Display_mRStabGround", getCanBit('0x402', byteIndex: 2, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("Display_mRStabiTransport", getCanBit('0x402', byteIndex: 2, bitIndex: 7) ? "ON" : "OFF"),

// Byte 3 – Flags
_diagRow("Display_mFTibiaTransport", getCanBit('0x402', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_mRTibiaTransport", getCanBit('0x402', byteIndex: 3, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_mFTibiaOut", getCanBit('0x402', byteIndex: 3, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_mRTibiaOut", getCanBit('0x402', byteIndex: 3, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("Display_mFContactSwingInc", getCanBit('0x402', byteIndex: 3, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_mRContactSwingInc", getCanBit('0x402', byteIndex: 3, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mAutoExtend", getCanBit('0x402', byteIndex: 3, bitIndex: 6) ? "ON" : "OFF"),
_diagRow("mAutoUnload", getCanBit('0x402', byteIndex: 3, bitIndex: 7) ? "ON" : "OFF"),

// Bytes 4–7 – Single-byte values
_diagRow("Display_CraneModel", getCanValue('0x402', byteIndex: 4, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_swl", getCanValue('0x402', byteIndex: 5, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_curSwl", getCanValue('0x402', byteIndex: 6, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_curSwlLoad", getCanValue('0x402', byteIndex: 7, length: 1, scale: 1).toStringAsFixed(0)),

_diagRow("Display_FRONTstabOutreach", getCanValue('0x403', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_FRONTpgh1", getCanValue('0x403', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_FRONTactualLoadCorr", getCanValue('0x403', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_LH_FrontCraneHighHigherPoint", getCanValue('0x403', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_REARstabOutreach", getCanValue('0x404', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_REARpgh1", getCanValue('0x404', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_REARactualLoadCorr", getCanValue('0x404', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_LH_RearCraneHighHigherPoint", getCanValue('0x404', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_TOTALtime_LSB", getCanValue('0x405', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_TOTALtime_MSB", getCanValue('0x405', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_WORKtime_LSB", getCanValue('0x405', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_WORKtime_MSB", getCanValue('0x405', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),


_diagRow("Display_FRONTactualLoad", getCanValue('0x407', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_REARactualLoad", getCanValue('0x407', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_possibleLoad", getCanValue('0x407', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_FRONTpossibleLoad", getCanValue('0x407', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_REARpossibleLoad", getCanValue('0x408', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_EV2040", getCanBit('0x408', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_Speed_Command", getCanBit('0x408', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),

_diagRow("Display_TOTALCycles_LSB", getCanValue('0x409', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_TOTALCycles_MSB", getCanValue('0x409', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_TOTALDayWCycles_LSB", getCanValue('0x409', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_TOTALDayWCycles_MSB", getCanValue('0x409', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_TOTALUserCycles_LSB", getCanValue('0x40A', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_TOTALUserCycles_MSB", getCanValue('0x40A', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_TOTALUserDayWCycles_LSB", getCanValue('0x40A', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_TOTALUserDayWCycles_MSB", getCanValue('0x40A', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_FrontCraneTransport", getCanValue('0x40B', byteIndex: 0, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_RearCraneTransport", getCanValue('0x40B', byteIndex: 1, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_EnableTransport", getCanBit('0x40B', byteIndex: 2, bitIndex: 0) ? "ON" : "OFF"),
_diagRow("Display_DisableTransport", getCanBit('0x40B', byteIndex: 2, bitIndex: 1) ? "ON" : "OFF"),
_diagRow("Display_paAutoDeploy", getCanBit('0x40B', byteIndex: 2, bitIndex: 2) ? "ON" : "OFF"),
_diagRow("Display_paBinLoader", getCanBit('0x40B', byteIndex: 2, bitIndex: 3) ? "ON" : "OFF"),
_diagRow("mTippingModeRemember", getCanBit('0x40B', byteIndex: 2, bitIndex: 4) ? "ON" : "OFF"),
_diagRow("Display_TestMode", getCanBit('0x40B', byteIndex: 2, bitIndex: 5) ? "ON" : "OFF"),
_diagRow("mRearFemurAngleRef", getCanValue('0x40B', byteIndex: 3, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("mFrontFemurAngleRef", getCanValue('0x40B', byteIndex: 4, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("mRearCraneFrameAngleRef", getCanValue('0x40B', byteIndex: 5, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("mFrontCraneFrameAngleRef", getCanValue('0x40B', byteIndex: 6, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("mFrontCraneFrameAngleRef1", getCanValue('0x40B', byteIndex: 7, length: 1, scale: 1).toStringAsFixed(0)),

_diagRow("Display_FRONTactualForce", getCanValue('0x40C', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_REARactualForce", getCanValue('0x40C', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("FrontChain1", getCanValue('0x40C', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("RearChain1", getCanValue('0x40C', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_RadioType", getCanValue('0x40D', byteIndex: 0, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("paOnsideLimit", getCanValue('0x40D', byteIndex: 1, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("Display_CraneSideLift", getCanValue('0x40D', byteIndex: 2, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("mRearCraneFrameAngleRef1", getCanValue('0x40D', byteIndex: 3, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("VirtualAutoChassyAngle_F", getCanValue('0x40D', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("VirtualAutoChassyAngle_R", getCanValue('0x40D', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("mRearCraneFrameAngleRef2", getCanValue('0x40E', byteIndex: 0, length: 1, scale: 1).toStringAsFixed(0)),
_diagRow("mFrontCraneFrameAngleRef2", getCanValue('0x40E', byteIndex: 1, length: 1, scale: 1).toStringAsFixed(0)),

_diagRow("Display_FrontEquipTareWeight", getCanValue('0x411', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_RearEquipTareWeight", getCanValue('0x411', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_FrontTareWeight", getCanValue('0x411', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_RearTareWeight", getCanValue('0x411', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_timDetectMvt", getCanValue('0x412', byteIndex: 1, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_WeightIcon", getCanBit('0x412', byteIndex: 3, bitIndex: 0) ? "ON" : "OFF"),

_diagRow("Display_FRONTLoadCorrTare", getCanValue('0x413', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_REARLoadCorrTare", getCanValue('0x413', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_FRONTLoadTare", getCanValue('0x413', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_REARLoadTare", getCanValue('0x413', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),

_diagRow("Display_Reply", getCanValue('0x161', byteIndex: 0, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_ReplyCnt", getCanValue('0x161', byteIndex: 2, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_ReplyA", getCanValue('0x161', byteIndex: 4, length: 2, scale: 1).toStringAsFixed(0)),
_diagRow("Display_ReplyB", getCanValue('0x161', byteIndex: 6, length: 2, scale: 1).toStringAsFixed(0)),





*/



     