platform :ios, '15.5'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!
use_modular_headers!

# Load Flutter's iOS pod helper
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
